services:
  iptv-epg:
    image: ghcr.io/konkolorado/iptv-epg:main
    restart: no
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - OUTPUT_PATH=data/tvguide.xml
      - MAX_CONNECTIONS=3
      #- "CRON_SCHEDULE=43 4 * * *"
      #- SITE=tvguide.com
      - DAYS=2
      - CHANNELS_FILE=./channels.xml
    volumes:
      - '${PWD}/tvguide:/epg/data'

